services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring
    depends_on:
      - chatservice

  chatservice:
    image: elitekaycy/chatservice:latest
    ports:
      - "8085:8085"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  prometheus-data: {}
  grafana-data: {}

networks:
  monitoring:
    driver: bridge
